export { default as ArchHero }     from './ArchHero'
export { default as ArchServices } from './ArchServices'
export { ArchProcess }             from './ArchProcess'
export { ArchWhyUs }               from './ArchWhyUs'
export { default as ArchProjects } from './ArchProjects'
export { default as ArchCTA }      from './ArchCTA'
